function stn = get_ncep_narr(stn)
%function stn = get_ncep_narr(stn)

  datapath = get_thesis_path('../data');

  LONS = load(fullfile(datapath,'NCEP_NARR_lon.dat'));
  LATS = load(fullfile(datapath,'NCEP_NARR_lat.dat'));

  [lonix,latix] = gridnbhd_km(LONS,LATS,station.lon,station.lat,0);


  % http://nomads.ncdc.noaa.gov/thredds/dodsC/narr/201001/20100119/narr-a_221_20100119_0000_000.grb.ascii?Downward_longwave_radiation_flux[0:1:0][lonix][latix],Downward_shortwave_radiation_flux[0:1:0][lonix][latix],Evaporation[0:1:0][lonix][latix],Latent_heat_flux[0:1:0][lonix][latix],Precipitation_rate[0:1:0][lonix][latix],Pressure_nearest_grid_point[0:1:0][lonix][latix],Relative_humidity[0:1:0][0:1:0][lonix][latix],Sensible_heat_flux[0:1:0][lonix][latix],Specific_humidity_height_above_ground[0:1:0][0:1:0][lonix][latix],Total_cloud_cover[0:1:0][lonix][latix],Total_precipitation[0:1:0][lonix][latix],u_wind_height_above_ground[0:1:0][0:1:0][lonix][latix],Upward_long_wave_radiation_flux_surface[0:1:0][lonix][latix],Upward_short_wave_radiation_flux_surface[0:1:0][lonix][latix],v_wind_height_above_ground[0:1:0][0:1:0][lonix][latix]

  % http://nomads.ncdc.noaa.gov/thredds/dodsC/narr/201001/20100119/narr-a_221_20100119_0000_000.grb.dods?Downward_longwave_radiation_flux[0:1:0][lonix][latix],Downward_shortwave_radiation_flux[0:1:0][lonix][latix],Evaporation[0:1:0][lonix][latix],Latent_heat_flux[0:1:0][lonix][latix],Precipitation_rate[0:1:0][lonix][latix],Pressure_nearest_grid_point[0:1:0][lonix][latix],Relative_humidity[0:1:0][0:1:0][lonix][latix],Sensible_heat_flux[0:1:0][lonix][latix],Specific_humidity_height_above_ground[0:1:0][0:1:0][lonix][latix],Total_cloud_cover[0:1:0][lonix][latix],Total_precipitation[0:1:0][lonix][latix],u_wind_height_above_ground[0:1:0][0:1:0][lonix][latix],Upward_long_wave_radiation_flux_surface[0:1:0][lonix][latix],Upward_short_wave_radiation_flux_surface[0:1:0][lonix][latix],v_wind_height_above_ground[0:1:0][0:1:0][lonix][latix]

  % whole_dataquery = sprintf('Downward_longwave_radiation_flux[0:1:0][%g][%g],Downward_shortwave_radiation_flux[0:1:0][%g][%g],Evaporation[0:1:0][%g][%g],Latent_heat_flux[0:1:0][%g][%g],Precipitation_rate[0:1:0][%g][%g],Pressure_nearest_grid_point[0:1:0][%g][%g],Relative_humidity[0:1:0][0:1:0][%g][%g],Sensible_heat_flux[0:1:0][%g][%g],Specific_humidity_height_above_ground[0:1:0][0:1:0][%g][%g],Total_cloud_cover[0:1:0][%g][%g],Total_precipitation[0:1:0][%g][%g],u_wind_height_above_ground[0:1:0][0:1:0][%g][%g],Upward_long_wave_radiation_flux_surface[0:1:0][%g][%g],Upward_short_wave_radiation_flux_surface[0:1:0][%g][%g],v_wind_height_above_ground[0:1:0][0:1:0][%g][%g]',lonix,latix);

  vars = { ...
      'Dew_point_temperature[0][0]', ...
      'Downward_longwave_radiation_flux[0]', ...
      'Downward_shortwave_radiation_flux[0]', ...
      'Evaporation[0]', ...
      'Latent_heat_flux[0]', ...
      'Precipitation_rate[0]', ...
      'Pressure_nearest_grid_point[0]', ...
      'Relative_humidity[0][0]', ...
      'Sensible_heat_flux[0]', ...
      'Specific_humidity_height_above_ground[0][0]', ...
      'Total_cloud_cover[0]', ...
      'Total_precipitation[0]', ...
      'u_wind_height_above_ground[0][0]', ...
      'Upward_long_wave_radiation_flux_surface[0]', ...
      'Upward_short_wave_radiation_flux_surface[0]', ...
      'v_wind_height_above_ground[0][0]', ...
         };

  begdt = datenum(1987,1,1);
  enddt = floor(now);

  dts = begdt:(3/24):enddt;
  [yrs,mos,dys,hrs,mis,scs] = datevec(dts);
  jds = floor(dts) - datenum(yrs,1,1) + 1;

  for ix = 1:length(dts)
    qbase = sprintf('http://nomads.ncdc.noaa.gov/thredds/dodsC/narr/%04d%02d/%04d%02d%02d/narr-a_221_%04d%02d%02d_%02d00_000.grb.ascii', ...
                        yrs(ix),mos(ix),yrs(ix),mos(ix),dys(ix),yrs(ix),mos(ix),dys(ix),hrs(ix));
    for vix = 1:length(vars)
      dataquery = sprintf('%s?%s[%g][%g]', qbase, vars{vix}, lonix, latix);
    end;
  end;

return;
