function stns = load_haus_waves
%function stns = load_haus_waves

  datapath = get_thesis_path('../data');
  hauspath = fullfile(datapath,'haus_waves');

  stns.station_names = { ...
      'bhwv1', ...
      'bhwv2', ...
      'bhwv3', ...
      'bhwv4', ...
      'bhwv5', ...
      'bhwv6', ...
      'bhwv7', ...
      'bhwv8', ...
                   };

  stns.station_long_names = { ...
      'Cluster-1 (bottom)', ...
      'Cluster-2 (bottom)', ...
      'Cluster-3 (surface)', ...
      'Cluster-4 (bottom)', ...
      'Offshore-5 (botm-float)', ...
      'Inshore-6 (bottom)', ...
      'South-7 (surface)', ...
      'South-8 (bottom)', ...
                   };

  stns.coords_dms = [ ...
      -80 06 36.3 ;  25 30 02.1 ; ...
      -80 06 22.2 ;  25 29 53.7 ; ...
      -80 06 08.9 ;  25 29 56.7 ; ...
      -80 06 31.2 ;  25 29 55.2 ; ...
      -80 05 53.2 ;  25 23 48.4 ; ...
      -80 08 30.2 ;  25 28 46.0 ; ...
      -80 07 01.2 ;  25 26 08.8 ; ...
      -80 06 48.4 ;  25 28 13.7 ; ...
                    ];
  stns.coords = dms2degrees(stns.coords_dms);

  stns.lons = stns.coords(1:2:end);
  stns.lats = stns.coords(2:2:end);

  stns.depths = [ ...
      10.0 ...
      14.0 ...
      15.0 ...
      8.8 ...
      100 ...
      6.0 ...
      15.0 ...
      9.0 ...
                ];

  %% Load available data courtesy of Dr. B. Haus (pers. comm.)

  stns.bhwv4.station_name = stns.station_names{4};
  stns.bhwv4.lon = stns.lons(4);
  stns.bhwv4.lat = stns.lats(4);
  stns.bhwv4.depth = stns.depths(4);
  matfname = fullfile(hauspath,'Hs_SNTK.mat');
  if ( ~exist(matfname) )
    warning('Station bhwv4: No data file "%s"',matfname);
  else
    load(matfname,'Hs_SNTK');
    stns.bhwv4.sontek_sigwavehgt.date = datenum(2005,3,19,17,0,0) + ([0:numel(Hs_SNTK)-1]'./24);
    stns.bhwv4.sontek_sigwavehgt.data = Hs_SNTK;
    Hs_SNTK=[]; clear Hs_SNTK;
  end;

  stns.bhwv3.station_name = stns.station_names{3};
  stns.bhwv3.lon = stns.lons(3);
  stns.bhwv3.lat = stns.lats(3);
  stns.bhwv3.depth = stns.depths(3);
  datfname = fullfile(hauspath,'Summarytas01290.txt');
  if ( ~exist(datfname) )
    warning('Station bhwv3: No data file "%s"',datfname);
  else
    stns.bhwv3 = get_triaxys_waves(datfname,stns.bhwv3);
  end;

  stns.bhwv7.station_name = stns.station_names{7};
  stns.bhwv7.lon = stns.lons(7);
  stns.bhwv7.lat = stns.lats(7);
  stns.bhwv7.depth = stns.depths(7);
  datfname = fullfile(hauspath,'Summarytab00651.txt');
  if ( ~exist(datfname) )
    warning('Station bhwv7: No data file "%s"',datfname);
  else
    stns.bhwv7 = get_triaxys_waves(datfname,stns.bhwv7);
  end;


return;
