function new_figs(stn)

  R = (1.00-0.08);
  cfac = 1.20;
  wfac = 1.20;
  lagoff = 0;

  [firstyr,ig,ig] = datevec(stn.fkeys_hycom_dt.date(1));
  [lastyr,ig,ig] = datevec(stn.fkeys_hycom_dt.date(end));
  dys = datenum(lastyr,12,31) - datenum(firstyr,1,1) + 1;

  plot_fluxes(stn,firstyr,1,dys,{'ndbc_sea_t'},[],...
              {...
                  'gom_hycom_qedt','fkeys_hycom_qedt',...
                  'netqf',...
                  'gom_hycom_qedt_netqf','fkeys_hycom_qedt_netqf',...
                  'gom_hycom_netqf','fkeys_hycom_netqf',...
                  'gom_hycom_qenetqf','fkeys_hycom_qenetqf',...
              },[],...
              {...
                  'NDBC sea temperature',...
                  'GoM 4km HYCOM + Stokes + Q_0','FKEYS 1km HYCOM + Stokes + Q_0',...
                  'HC(Q_0) (thermal siphon)',...
                  'GoM 4km HYCOM + Stokes + HC(Q_0)','FKEYS 1km HYCOM + Stokes + HC(Q_0)',...
                  'HC(GoM 4km HYCOM + Q_0)','HC(FKEYS 1km HYCOM + Q_0)',...
                  'HC(GoM 4km HYCOM + Stokes + Q_0)','HC(FKEYS 1km HYCOM + Stokes + Q_0)',...
              });
  appendtitlename(sprintf(' R:%g C:%g W:%g', R, cfac, wfac));
  if (lagoff); appendtitlename(sprintf(' lag:%d', lagoff)); end;


  plot_fluxes(stn,firstyr,1,dys,{'ndbc_sea_t'},[],...
              {...
                  'netqf',...
                  'gom_hycom_qenetqf','fkeys_hycom_qenetqf',...
              },[],...
              {...
                  'NDBC sea temperature',...
                  'HC(Q_0) (thermal siphon)',...
                  'HC(GoM 4km HYCOM + Stokes + Q_0)','HC(FKEYS 1km HYCOM + Stokes + Q_0)',...
              });
  appendtitlename(sprintf(' R:%g C:%g W:%g', R, cfac, wfac));
  if (lagoff); appendtitlename(sprintf(' lag:%d', lagoff)); end;

return;
